name: publish

on:
  pull_request:
  push:
    tags: ['v[0-9]+\.[0-9]+\.[0-9]+']

jobs:
  pypi:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Build binary and source distribution
        run: uv build

      - name: Publish to PyPI on tag
        if: ${{  }}
        run: |
          uv publish --no-progress \
          ${{ github.ref_type != 'tag' && '--dry-run' || '' }} \
          --trusted-publishing=always \
          dist/*
